### ISSUE TITLE
Endpoints

### ISSUE THREAD

**Issue by MingHaoC** [Meeting-Maker/Back_End#9]
- Create endpoint to get all candidate meeting

**Comment by MingHaoC** [comment]
need an endpoint to get vote related to a candidate meeting as well

**Comment by BoKlassen** [comment]
Need endpoint to get MeetingDetails, which would also allow us to see if a meetingID entered at /join is valid.

**Comment by MingHaoC** [comment]
Need to add an endpoint for comments
